apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    app: example # this should match the pod label in deployment.yml
  ports:
    - name: https
      port: 3000
      targetPort: 3000